repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - id: clang-format
        args: [--style=Google]
      - id: clang-tidy
      - id: oclint
      - id: uncrustify
      - id: cppcheck
      - id: cpplint
      - id: include-what-you-use


  # 3CMake Format (Ensures consistent CMake style)
  - repo: https://github.com/cheshirekow/cmake_format
    rev: v0.6.13
    hooks:
      - id: cmake-format
        args: [--in-place]

  # 4Prettier (Formats Markdown, YAML, JSON, etc.)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        args: [--write]

  # 5End-of-file Fixer (Ensures files end with a newline)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer

  # 6Trailing Whitespace Fixer
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace

  # 7Detect Large Files (Prevents accidental commits of huge files)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]  # Prevent committing files >500 KB

  # 8Detect Secrets (Prevent accidental commits of API keys or passwords)
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]

  # Gitlint (Ensure clean commit messages)
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.18.0
    hooks:
      - id: gitlint

  # ShellCheck (For checking shell scripts in the repo)
  - repo: https://github.com/koalaman/shellcheck
    rev: v0.9.0
    hooks:
      - id: shellcheck